apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: timer-getter
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/reverendyz/argo-test.git
        revision: HEAD
        files:
          - path: argocd/projects/project-b/project.yaml
  template:
    metadata:
      name: '{{project}}-app'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/reverendyz/argo-test.git
          targetRevision: HEAD
          ref: valuesRef
        - repoURL: https://github.com/reverendyz/helm-charts.git
          targetRevision: main
          path: sample-service/timer-api
          helm:
            valueFiles:
              - "$valuesRef/argocd/projects/{{project}}/defaults/values.yaml"
              - "$valuesRef/argocd/projects/{{project}}/overrides/values.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
