apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: timer-getter-project-a
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/reverendyz/argo-test.git
        revision: HEAD
        files:
          - path: argocd/projects/project-a/project.yaml
  template:
    metadata:
      name: '{{project}}-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/reverendyz/helm-charts.git
        targetRevision: HEAD
        path: sample-service/timer-api
        helm:
          valueFiles:
            - argocd/projects/{{project}}/defaults/values.yaml
            - argocd/projects/{{project}}/overrides/values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
